### ISSUE TITLE
Can't specify EU Region

### ISSUE THREAD

**Issue by zola-25** [agolaszewski/Seq.App.Mailgun#1]
We are getting a Forbidden response on our email requests. I think it is because this line:

`var sender = new MailgunSender(Domain, ApiKey);`

defaults to USA mailgun region. We are set to EU region. There is an overload to set it to EU region:

 `var sender = new MailgunSender(Domain, ApiKey, MailGunRegion.EU);`

 Maybe it should be a setting.

Thanks

**Comment by agolaszewski** [comment]
Hey. I have just pushed the code and now in build 43 it is possible to specify region.
